# Generated by Django 4.1.7 on 2024-02-07 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proyects',
            name='img',
            field=models.ImageField(upload_to='static/media/images/proyects'),
        ),
    ]
