# Generated by Django 4.1.7 on 2024-02-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0003_alter_member_cv_alter_member_profile_pic_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='proyects',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
