# Generated by Django 4.1.7 on 2024-02-08 07:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('port', '0004_proyects_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='cv',
            field=models.FileField(blank=True, null=True, upload_to='static/media/cv'),
        ),
        migrations.AlterField(
            model_name='member',
            name='profile_pic',
            field=models.ImageField(blank=True, null=True, upload_to='static/media/images'),
        ),
        migrations.AlterField(
            model_name='proyects',
            name='img',
            field=models.ImageField(upload_to='static/media/images/proyects'),
        ),
    ]
